name: Request
description: Submit new feature request
title: "[Request]: "
labels: ["request", "new triage"]
assignees:
  - octocat
body:
  - type: input
    id: persona
    attributes:
      label: Persona
      description: Who will need this feature
      placeholder: developer/ODM
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe your feature request in details
      placeholder: ex. setup script to install GPU driver
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Provide justification on why this feature is needed
      placeholder: ex. enable GPU
    validations:
      required: true
      
  - type: dropdown
    id: prioritization
    attributes:
      label: Prioritization
      description: Provide your request prioritization
      multiple: false
      options:
        - Must have
        - Good to have
    validations:
      required: true
