name: "New Task"
description: "I am breaking down task from user story"
title: '[Task]'
labels: ["enhancement","task"]
body:
- type: input
  attributes:
    label: Parent Issue
    description: Enter the link of the parent Github Issue
    placeholder: https://github.com/intel-sandbox/mv-ai-kit/issues/
  validations:
    required: true
- type: input
  attributes:
    label: Module
    description: Which module will this task falls under
  validations:
      required: true
- type: dropdown
  id: user
  attributes:
    label: As a
    description: Who will be use this feature
    options:
      - "developer: the developer of the tool i.e. CASE CSE"
      - "user: the user of the tool"
      - "consumer: the end users that will consume the output of the tool"
  validations:
    required: true

- type: textarea
  attributes:
    label: I want to
    description: Describe what does the persona wants to accomplish
    placeholder: define my own code pair
  validations:
      required: true

- type: textarea
  attributes:
    label: So that
    description: Describe why the persona needs this feature
    placeholder: the model can be fine tuned with my own instructions
  validations:
      required: true