name: "New Task"
description: "I am breaking down task from user story"
title: '[Task]'
labels: ["enhancement","task"]
body:
- type: input
  attributes:
    label: Parent Issue
    description: Enter the link of the parent Github Issue
    placeholder: https://github.com/intel-sandbox/mv-ai-kit/issues/
  validations:
    required: true
- type: input
  attributes:
    label: Module
    description: Which module will this task falls under
  validations:
      required: true
- type: textarea
  attributes:
    label: Task
    description: Describe what your code will accomplish
  validations:
      required: true
